site_url: https://ntn-boilerplate.netlify.app/
logo_url: https://ntn-boilerplate.netlify.app/icon.png

i18n:
  structure: multiple_files
  locales: [nl, fr]
  
publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: 'Google Sheet Id', name: 'sheet', widget: 'string', required: true }
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
  - name: 'locations'
    i18n: true
    label: 'Locations'
    folder: 'content/locations'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    # editor:
    #   preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
